# Generated by Django 2.1.3 on 2018-11-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_time', models.IntegerField(blank=True, null=True, verbose_name='借出时间')),
                ('pre_return', models.IntegerField(blank=True, null=True, verbose_name='预归还时间')),
                ('return_time', models.IntegerField(blank=True, null=True, verbose_name='归还时间')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='借出原因')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('belong', models.TextField(blank=True, primary_key=True, serialize=False, verbose_name='归属科室')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.TextField(primary_key=True, serialize=False, verbose_name='设备编号')),
                ('device_name', models.TextField(blank=True, null=True, verbose_name='设备名称')),
                ('device_pic', models.ImageField(blank=True, null=True, upload_to='device/', verbose_name='设备图片')),
                ('device_type', models.TextField(blank=True, null=True, verbose_name='设备类型')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='规格')),
                ('device_model', models.TextField(blank=True, null=True, verbose_name='设备型号')),
                ('warranty_date', models.IntegerField(blank=True, null=True, verbose_name='保修日期')),
                ('purchase_date', models.IntegerField(blank=True, null=True, verbose_name='采购日期')),
                ('registry_date', models.IntegerField(blank=True, null=True, verbose_name='登记日期')),
                ('location', models.TextField(blank=True, null=True, verbose_name='存放位置')),
                ('supplier', models.TextField(blank=True, null=True, verbose_name='供应商')),
                ('status', models.TextField(blank=True, null=True, verbose_name='设备状态')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_time', models.IntegerField(blank=True, null=True, verbose_name='维修时间')),
                ('repair_fin', models.IntegerField(blank=True, null=True, verbose_name='维修完成时间')),
                ('repair_man', models.TextField(blank=True, null=True, verbose_name='维修人')),
                ('repair_money', models.TextField(blank=True, null=True, verbose_name='维修金额')),
                ('repair_num', models.TextField(blank=True, null=True, verbose_name='维修人电话')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('user_name', models.TextField(blank=True, null=True, verbose_name='用户编号')),
                ('user_tel', models.TextField(blank=True, null=True, verbose_name='用户电话')),
                ('user_email', models.TextField(blank=True, null=True, verbose_name='用户邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='index.Device', verbose_name='设备编号')),
                ('scrap_reason', models.TextField(blank=True, null=True, verbose_name='报废原因')),
                ('available_year', models.IntegerField(blank=True, null=True, verbose_name='使用年限')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Device', verbose_name='设备编号'),
        ),
        migrations.AddField(
            model_name='device',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.Department', verbose_name='归属科室'),
        ),
        migrations.AddField(
            model_name='department',
            name='belong_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.User', verbose_name='科室联系人'),
        ),
        migrations.AddField(
            model_name='borrowmanage',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.Device', verbose_name='设备编号'),
        ),
        migrations.AddField(
            model_name='borrowmanage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.User', verbose_name='借出者'),
        ),
    ]
